In [1]:
import pandas as pd
%matplotlib inline 
import matplotlib.pyplot as plt

cross validation allow us to compare different machine learning method and get a sense of how well they will work in practise 

In [2]:
from sklearn.linear_model import LogisticRegression 

In [3]:
from sklearn.svm import SVC

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
import numpy as np

In [6]:
from sklearn.datasets import load_digits

In [7]:
digits=load_digits()

In [8]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.7)

In [11]:
LR=LogisticRegression()

In [12]:
svm=SVC()

In [13]:
rf=RandomForestClassifier()

In [14]:
LR.fit(x_train,y_train)

c:\MinGW\python32\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
LR.score(x_test,y_test)

0.9483306836248012

In [16]:
svm.fit(x_train,y_train)

SVC()

In [17]:
svm.score(x_test,y_test)

0.9769475357710652

In [18]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [19]:
rf.score(x_test,y_test)

0.958664546899841

when we iterate or again run the above code the data of x_trian test will change which lead to the change in the prediction for that we use the kfold algorithm to compare which datasets is best

In [20]:
from sklearn.model_selection import KFold

In [21]:
kf=KFold(n_splits=4)

In [22]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


here in the split we hve divided the data into 4 part where first is for train and other is test respectively 

In [23]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train, y_train)
    return model.score(x_test,y_test)

In [24]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

c:\MinGW\python32\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9483306836248012

In [25]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9769475357710652

In [26]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9634340222575517

In [27]:
from sklearn.model_selection import StratifiedKFold

In [28]:
folds=StratifiedKFold(n_splits=5)

In [29]:
scores_l=[]

In [30]:
scores_svm=[]

In [31]:
scores_rf=[]

In [32]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [33]:
scores_l

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.8941504178272981]

In [34]:
scores_svm

[0.4111111111111111,
 0.45,
 0.45403899721448465,
 0.44846796657381616,
 0.479108635097493]

In [35]:
scores_rf

[0.9277777777777778,
 0.9055555555555556,
 0.958217270194986,
 0.9637883008356546,
 0.9192200557103064]

In [36]:
from sklearn.model_selection import cross_val_score

In [37]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\MinGW\python32\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\MinGW\python32\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_opt

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93055556, 0.91666667, 0.9637883 , 0.96100279, 0.9275766 ])