In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn

In [2]:
df1=pd.read_csv("houseprice.csv")

In [3]:
df1


town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windson  2600  585000
6      west windson  2800  615000
7      west windson  3300  650000
8      west windson  3600  710000
9       robbinsvile  2600  575000
10      robbinsvile  2900  600000
11      robbinsvile  3100  620000
12      robbinsvile  3600  695000

In [4]:
df1['town']

0     monroe township
1     monroe township
2     monroe township
3     monroe township
4     monroe township
5        west windson
6        west windson
7        west windson
8        west windson
9         robbinsvile
10        robbinsvile
11        robbinsvile
12        robbinsvile
Name: town, dtype: object

In [5]:
dumies=pd.get_dummies(df1.town)
dumies

monroe township  robbinsvile  west windson
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [6]:
merged=pd.concat([df1,dumies],axis='columns')
merged

town  area   price  monroe township  robbinsvile  west windson
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windson  2600  585000            False        False          True
6      west windson  2800  615000            False        False          True
7      west windson  3300  650000            False        False          True
8      west windson  3600  710000            False        False          True
9       robbinsvile  2600  575000            False         True         False
10      robbinsvile  2900  600000            False         True         False
11      robbinsvile  3100  620000            False         True         False
12      robbinsvile  3600  695000            False         True         False

first of all we have to drop the town coloum since now we donot required that town coloum 
since our model work on mathematical data not on that categorical data

second thing is that we have to drop one of these dumy variable coloum 
the reason behind this is that 
Dummy Variable Trap: 
The Dummy variable trap is a scenario where there are attributes that are highly correlated (Multicollinear) and one variable predicts the value of others. When we use one-hot encoding for handling the categorical data, then one dummy variable (attribute) can be predicted with the help of other dummy variables. Hence, one dummy variable is highly correlated with other dummy variables. Using all dummy variables for regression models leads to a dummy variable trap. So, the regression models should be designed to exclude one dummy variable.

In [7]:
final=merged.drop(['town','west windson'],axis='columns')

In [8]:
final 

area   price  monroe township  robbinsvile
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [10]:
x=final.drop(['price'],axis='columns')


In [11]:
x

area  monroe township  robbinsvile
0   2600             True        False
1   3000             True        False
2   3200             True        False
3   3600             True        False
4   4000             True        False
5   2600            False        False
6   2800            False        False
7   3300            False        False
8   3600            False        False
9   2600            False         True
10  2900            False         True
11  3100            False         True
12  3600            False         True

In [12]:
y=final.price

In [13]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [14]:
model.fit(x,y)

LinearRegression()

In [15]:
model.coef_

array([   126.89744141, -40013.97548914, -14327.56396474])

In [16]:
model.intercept_

249790.36766292527

In [17]:
model.predict([[2800,0,1]])

c:\MinGW\python32\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [18]:
model.predict([[2800,0,0]])

c:\MinGW\python32\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([605103.20361213])

In [19]:
model.predict([[2800,1,0]])

c:\MinGW\python32\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([565089.22812299])

In [20]:
model.predict([[2600,1,0]])

c:\MinGW\python32\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([539709.7398409])

In [21]:
model.score(x,y)


0.9573929037221872

"""
it will calcuate the predicted value for all the rows and then it will compare predictor 
value with the actual value which is y after that it will use some formula to calculate the 
score 
here 0.95 show that the model is 95 percent accurate 
"""

In [22]:
df1

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windson  2600  585000
6      west windson  2800  615000
7      west windson  3300  650000
8      west windson  3600  710000
9       robbinsvile  2600  575000
10      robbinsvile  2900  600000
11      robbinsvile  3100  620000
12      robbinsvile  3600  695000

In [168]:
# using sklearn and hot encoder 

In [169]:
from sklearn.preprocessing import LabelEncoder 

In [170]:
le=LabelEncoder()

In [171]:
df1

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windson  2600  585000
6      west windson  2800  615000
7      west windson  3300  650000
8      west windson  3600  710000
9       robbinsvile  2600  575000
10      robbinsvile  2900  600000
11      robbinsvile  3100  620000
12      robbinsvile  3600  695000

In [172]:
dfle=df1

In [173]:
print(dfle)
print()
print(df1)

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windson  2600  585000
6      west windson  2800  615000
7      west windson  3300  650000
8      west windson  3600  710000
9       robbinsvile  2600  575000
10      robbinsvile  2900  600000
11      robbinsvile  3100  620000
12      robbinsvile  3600  695000

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windson  2600  585000
6      west windson  2800  615000
7      west windson  3300  650000
8      west windson  3600  710000
9       robbinsvile  2600  575000
10      robbinsvile  2900  600000
11      robbinsvile  3100  620000
12      robbinsvile  3600  695000


In [174]:
dfle.town=le.fit_transform(dfle.town)

In [181]:
print(dfle.town)
print("hii")
print(df1.town)

0     0
1     0
2     0
3     0
4     0
5     2
6     2
7     2
8     2
9     1
10    1
11    1
12    1
Name: town, dtype: int32
hii
0     0
1     0
2     0
3     0
4     0
5     2
6     2
7     2
8     2
9     1
10    1
11    1
12    1
Name: town, dtype: int32


In [182]:
print(df1)
x=df1[['town','area']].values
print(x)
print(x.ndim)
print(type(x))

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000
[[   0 2600]
 [   0 3000]
 [   0 3200]
 [   0 3600]
 [   0 4000]
 [   2 2600]
 [   2 2800]
 [   2 3300]
 [   2 3600]
 [   1 2600]
 [   1 2900]
 [   1 3100]
 [   1 3600]]
2
<class 'numpy.ndarray'>


here above if we use the .values it become the array of numpy data type 
otherwise it is a array or dataframe of pandas series 

In [183]:
y=df1['price']

In [184]:
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [185]:
from sklearn.preprocessing import OneHotEncoder

In [186]:
oho=OneHotEncoder

In [188]:
oho=OneHotEncoder(categorical_features=[0])
oho=fit.transform(x).toarray()


TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'categorical_features'